# Generated by Django 4.1 on 2022-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baromessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='last_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='last_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
