
# Generated by Django 3.2 on 2023-03-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baromessages', '0002_messageroom_status_alter_messageroom_last_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
