# Generated by Django 4.1 on 2022-10-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0002_reviewresult_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='q1',
            new_name='q_1',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q2',
            new_name='q_2',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q3',
            new_name='q_3',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q4',
            new_name='q_4',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q5',
            new_name='q_5',
        ),
    ]
