# Generated by Django 4.1 on 2022-11-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0003_rename_q1_review_q_1_rename_q2_review_q_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewresult',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
