# Generated by Django 3.2 on 2022-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0005_reviewresult_review_count_alter_reviewresult_av_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='localCity',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='localGu',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
