# Generated by Django 4.1 on 2022-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0006_auto_20221118_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='localCity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='localGu',
        ),
        migrations.AddField(
            model_name='product',
            name='local_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='local_gu',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
